#import os
#from ConfigParser import ConfigParser

env = Environment(tools = ['Inkcards', 'Tiling'])

env['INKCARDS'] = {
    'card 1': {
        'front': ['Front Layer', '1', 'Frame'],
	'rear' : ['Rear Layer', 'Frame']
    },
    'card 2': {
        'front': ['Front Layer', '2', 'Frame'],
	'rear' : ['Rear Layer', 'Frame']
    }
}

def get_layers_per_card():
    config = ConfigParser()
    #config.read(os.path.join('..', 'src', str(confFile)))
    env['INKCARDS'] =  { 'card 1' : {'front' : ['Layer 1']}} # <-- Generate this from the conf file so that it's used by this and the inkscape extension. 

cards=[]
for idx, c in enumerate(env['INKCARDS'], 1): #enumerate(cardsconfig.sections(), 1):
    card = {}
    card['front'] = env.Inkcards('%s.front.svg'%c, 'testcards.svg', CARD_NB=idx, CARD_SIDE='front')
    card['rear'] = env.Inkcards('%s.rear.svg'%c, 'testcards.svg', CARD_NB=idx, CARD_SIDE='rear')
    cards.append(card)

front = [card['front'] for card in cards]
front = env.Tiling('testcards-front', front, INKCARDS_ROT=90)

rear = [card['rear'] for card in cards]
rear = env.Tiling('testcards-rear', rear, INKCARDS_ROT=-90)
